services:

  db:
    image: postgres
    restart: always
 
    environment:
      POSTGRES_DB: curso_docker
      POSTGRES_USER: docker_usr
      POSTGRES_PASSWORD: docker_pwd

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8082